package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import com.mopub.nativeads.MoPubNativeAdPositioning.MoPubClientPositioning;
import com.mopub.volley.BuildConfig;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@zzadh
public final class amn {
    public static final amd<Long> A = amd.a(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final amd<Boolean> B = amd.a(1, "gads:video:aggressive_media_codec_release", Boolean.valueOf(false));
    public static final amd<Boolean> C = amd.a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    public static final amd<Boolean> D = amd.a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
    public static final amd<String> E = amd.a(1, "gads:video:codec_query_mime_types", "");
    public static final amd<Integer> F = amd.a(1, "gads:video:codec_query_minimum_version", 16);
    public static final amd<Boolean> G = amd.a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> H = amd.a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    public static final amd<String> I = amd.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final amd<String> J = amd.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final amd<String> K = amd.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final amd<String> L = amd.a(1, "gad:mraid:version", "2.0");
    public static final amd<Boolean> M = amd.a(1, "gads:mraid:unload", Boolean.valueOf(false));
    public static final amd<Boolean> N = amd.a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    public static final amd<String> O = amd.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final amd<Boolean> P = amd.a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    public static final amd<Boolean> Q = amd.a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    public static final amd<Integer> R = amd.a(0, "gads:content_length_weight", 1);
    public static final amd<Integer> S = amd.a(0, "gads:content_age_weight", 1);
    public static final amd<Integer> T = amd.a(0, "gads:min_content_len", 11);
    public static final amd<Integer> U = amd.a(0, "gads:fingerprint_number", 10);
    public static final amd<Integer> V = amd.a(0, "gads:sleep_sec", 10);
    public static final amd<Boolean> W = amd.a(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
    public static final amd<Integer> X = amd.a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final amd<Boolean> Y = amd.a(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
    public static final amd<Integer> Z = amd.a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final amd<String> a = amd.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final amd<Boolean> aA = amd.a(0, "gads:corewebview:javascript_engine", Boolean.valueOf(false));
    public static final amd<Boolean> aB = amd.a(1, "gad:webview:inject_scripts", Boolean.valueOf(false));
    public static final amd<Boolean> aC = amd.a(0, "gads:webview:permission:disabled", Boolean.valueOf(false));
    public static final amd<Boolean> aD = amd.a(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
    public static final amd<Long> aE = amd.a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final amd<Boolean> aF = amd.a(1, "gads:rewarded:ad_metadata_enabled", Boolean.valueOf(false));
    public static final amd<Boolean> aG = amd.a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    public static final amd<Long> aH = amd.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final amd<Long> aI = amd.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final amd<Boolean> aJ = amd.a(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
    public static final amd<Long> aK = amd.a(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final amd<Boolean> aL = amd.a(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
    public static final amd<Boolean> aM = amd.a(1, "gads:enable_ad_loader_manager", Boolean.valueOf(true));
    public static final amd<Boolean> aN = amd.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> aO = amd.a(1, "gads:ad_manager:admob_extra:new_bundle", Boolean.valueOf(true));
    public static final amd<Long> aP = amd.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final amd<Boolean> aQ = amd.a(1, "gads:interstitial_ad_immersive_mode", Boolean.valueOf(true));
    public static final amd<Boolean> aR = amd.a(1, "gads:custom_close_blocking:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> aS = amd.a(1, "gads:disabling_closable_area:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> aT = amd.a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> aU = amd.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    public static final amd<String> aV = amd.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final amd<String> aW = amd.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final amd<Integer> aX = amd.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final amd<Integer> aY = amd.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final amd<Integer> aZ = amd.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final amd<Integer> aa = amd.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final amd<String> ab = amd.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final amd<String> ac = amd.a(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final amd<Boolean> ad = amd.a(0, "gad:app_index_enabled", Boolean.valueOf(true));
    public static final amd<Boolean> ae = amd.a(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
    public static final amd<Boolean> af = amd.a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    public static final amd<Long> ag = amd.a(0, "gads:app_index:timeout_ms", 1000);
    public static final amd<Boolean> ah = amd.a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> ai = amd.a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    public static final amd<Boolean> aj = amd.a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    public static final amd<Boolean> ak = amd.a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    public static final amd<Boolean> al = amd.a(1, "gads:sai:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> am = amd.a(1, "gads:sai:banner_ad_enabled", Boolean.valueOf(true));
    public static final amd<Boolean> an = amd.a(1, "gads:sai:native_ad_enabled", Boolean.valueOf(true));
    public static final amd<Boolean> ao = amd.a(1, "gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
    public static final amd<Boolean> ap = amd.a(1, "gads:sai:rewardedvideo_ad_enabled", Boolean.valueOf(true));
    public static final amd<String> aq = amd.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final amd<String> ar = amd.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final amd<Boolean> as = amd.a(1, "gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
    public static final amd<Boolean> at = amd.a(1, "gads:sai:using_macro:enabled", Boolean.valueOf(false));
    public static final amd<String> au = amd.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final amd<Long> av = amd.a(1, "gads:sai:timeout_ms", -1);
    public static final amd<Integer> aw = amd.a(1, "gads:sai:scion_thread_pool_size", 5);
    public static final amd<Boolean> ax = amd.a(1, "gads:x_seconds_rewarded:enable", Boolean.valueOf(false));
    public static final amd<Boolean> ay = amd.a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    public static final amd<Boolean> az = amd.a(0, "gads:corewebview:adwebview_factory:enable", Boolean.valueOf(false));
    public static final amd<Boolean> b = amd.a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final amd<Long> bA = amd.a(0, "gads:ad_loader:timeout_ms", 60000);
    public static final amd<Long> bB = amd.a(0, "gads:rendering:timeout_ms", 60000);
    public static final amd<Boolean> bC = amd.a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final amd<Long> bD = amd.a(1, "gads:gestures:task_timeout", 2000);
    public static final amd<Boolean> bE = amd.a(1, "gads:gestures:asig:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> bF = amd.a(1, "gads:gestures:ans:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> bG = amd.a(1, "gads:gestures:tos:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> bH = amd.a(1, "gads:signal:app_permissions:disabled", Boolean.valueOf(false));
    public static final amd<Boolean> bI = amd.a(1, "gads:gestures:inthex:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> bJ = amd.a(1, "gads:gestures:hpk:enabled", Boolean.valueOf(true));
    public static final amd<String> bK = amd.a(1, "gads:gestures:pk", "");
    public static final amd<Boolean> bL = amd.a(1, "gads:gestures:bs:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> bM = amd.a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> bN = amd.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> bO = amd.a(0, "gass:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> bP = amd.a(0, "gass:enable_int_signal", Boolean.valueOf(true));
    public static final amd<Boolean> bQ = amd.a(0, "gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    public static final amd<Boolean> bR = amd.a(0, "gads:support_screen_shot", Boolean.valueOf(true));
    public static final amd<Boolean> bS = amd.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    public static final amd<String> bT = amd.a(1, "gads:sdk_core_constants:caps", "");
    public static final amd<Long> bU = amd.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final amd<Boolean> bV = amd.a(0, "gads:js_flags:mf", Boolean.valueOf(false));
    public static final amd<Boolean> bW = amd.a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    public static final amd<String> bX = amd.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final amd<String> bY = amd.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final amd<Boolean> bZ = amd.a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    public static final amd<String> ba = amd.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final amd<Integer> bb = amd.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final amd<Integer> bc = amd.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final amd<Long> bd = amd.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final amd<Long> be = amd.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final amd<Float> bf = amd.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final amd<Float> bg = amd.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final amd<Boolean> bh = amd.a(0, "gads:debug_logging_feature:enable", Boolean.valueOf(false));
    public static final amd<Boolean> bi = amd.a(0, "gads:debug_logging_feature:intercept_web_view", Boolean.valueOf(false));
    public static final amd<String> bj = amd.a(1, "gads:spherical_video:vertex_shader", "");
    public static final amd<String> bk = amd.a(1, "gads:spherical_video:fragment_shader", "");
    public static final amd<Boolean> bl = amd.a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final amd<Boolean> bm = amd.a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    public static final amd<Long> bn = amd.a(1, "gads:position_watcher:throttle_ms", 200);
    public static final amd<Boolean> bo = amd.a(1, "gads:include_lock_screen_apps_for_visibility", Boolean.valueOf(true));
    public static final amd<Boolean> bp = amd.a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    public static final amd<Long> bq = amd.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final amd<Boolean> br = amd.a(1, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> bs = amd.a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    public static final amd<Boolean> bt = amd.a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> bu = amd.a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    public static final amd<Long> bv = amd.a(1, "gads:network:network_prediction_timeout_ms", 2000);
    public static final amd<Boolean> bw = amd.a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    public static final amd<Boolean> bx = amd.a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    public static final amd<Boolean> by = amd.a(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
    public static final amd<Long> bz = amd.a(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final amd<Boolean> c = amd.a(0, "gads:report_dynamite_crash_in_background_thread", Boolean.valueOf(false));
    public static final amd<Long> cA = amd.a(1, "gads:parental_controls:timeout", 2000);
    public static final amd<Boolean> cB = amd.a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    public static final amd<Boolean> cC = amd.a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> cD = amd.a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    public static final amd<Boolean> cE = amd.a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    public static final amd<Boolean> cF = amd.a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    public static final amd<Long> cG = amd.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final amd<Boolean> cH = amd.a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    public static final amd<Boolean> cI = amd.a(1, "gads:http_assets_cache:enabled", Boolean.valueOf(false));
    public static final amd<String> cJ = amd.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final amd<Integer> cK = amd.a(1, "gads:http_assets_cache:time_out", 100);
    public static final amd<Boolean> cL = amd.a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> cM = amd.a(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> cN = amd.a(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
    public static final amd<Boolean> cO = amd.a(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> cP = amd.a(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> cQ = amd.a(1, "gads:debug_hold_gesture:enabled", Boolean.valueOf(false));
    public static final amd<Long> cR = amd.a(1, "gads:debug_hold_gesture:time_millis", 2000);
    public static final amd<String> cS = amd.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final amd<String> cT = amd.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final amd<String> cU = amd.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final amd<String> cV = amd.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final amd<Integer> cW = amd.a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final amd<Integer> cX = amd.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final amd<Boolean> cY = amd.a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    public static final amd<Boolean> cZ = amd.a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    public static final amd<Boolean> ca = amd.a(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
    public static final amd<Boolean> cb = amd.a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    public static final amd<Integer> cc = amd.a(1, "gads:native_video_load_timeout", 10);
    public static final amd<Integer> cd = amd.a(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final amd<String> ce = amd.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final amd<Boolean> cf = amd.a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    public static final amd<Boolean> cg = amd.a(1, "gads:enable_store_active_view_state", Boolean.valueOf(false));
    public static final amd<Boolean> ch = amd.a(1, "gads:enable_singleton_broadcast_receiver", Boolean.valueOf(false));
    public static final amd<Boolean> ci = amd.a(1, "gads:native:overlay_new_fix:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> cj = amd.a(1, "gads:native:count_impression_for_assets", Boolean.valueOf(false));
    public static final amd<Boolean> ck = amd.a(1, "gads:native:custom_one_point_five_click:enable", Boolean.valueOf(true));
    public static final amd<Boolean> cl = amd.a(1, "gads:unified_native_ad:enable", Boolean.valueOf(true));
    public static final amd<Boolean> cm = amd.a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    public static final amd<Boolean> cn = amd.a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    public static final amd<Long> co = amd.a(0, "gads:method_tracing:duration_ms", 30000);
    public static final amd<Integer> cp = amd.a(0, "gads:method_tracing:count", 5);
    public static final amd<Integer> cq = amd.a(0, "gads:method_tracing:filesize", 134217728);
    public static final amd<Long> cr = amd.a(1, "gads:auto_location_timeout", 2000);
    public static final amd<Boolean> cs = amd.a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    public static final amd<Long> ct = amd.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final amd<String> cu = amd.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final amd<String> cv = amd.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final amd<String> cw = amd.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final amd<String> cx = amd.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final amd<String> cy = amd.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final amd<Long> cz = amd.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final amd<Boolean> d = amd.a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    private static final amd<String> dA = amd.a(0, "gads:video_stream_cache:experiment_id");
    private static final amd<Boolean> dB = amd.a(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
    private static final amd<Float> dC = amd.a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static final amd<String> dD = amd.a(0, "gads:ad_id_app_context:experiment_id");
    private static final amd<String> dE = amd.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static final amd<Boolean> dF = amd.a(0, "gads:ad_id_use_shared_preference:enabled", Boolean.valueOf(false));
    private static final amd<Float> dG = amd.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static final amd<Boolean> dH = amd.a(0, "gads:ad_id_use_persistent_service:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> dI = amd.a(0, "gads:ad_id:use_ipc:enabled", Boolean.valueOf(false));
    private static final amd<String> dJ = amd.b(0, "gads:looper_for_gms_client:experiment_id");
    private static final amd<Boolean> dK = amd.a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    private static final amd<String> dL = amd.a(0, "gads:app_index:experiment_id");
    private static final amd<String> dM = amd.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    private static final amd<String> dN = amd.a(0, "gads:interstitial_follow_url:experiment_id");
    private static final amd<Boolean> dO = amd.a(0, "gads:analytics_enabled", Boolean.valueOf(true));
    private static final amd<Integer> dP = amd.a(0, "gads:webview_cache_version", 0);
    private static final amd<String> dQ = amd.b(0, "gads:pan:experiment_id");
    private static final amd<Boolean> dR = amd.a(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    private static final amd<Boolean> dS = amd.a(1, "gads:impression_optimization_enabled", Boolean.valueOf(false));
    private static final amd<String> dT = amd.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final amd<Integer> dU = amd.a(1, "gads:banner_ad_pool:max_queues", 3);
    private static final amd<Integer> dV = amd.a(1, "gads:banner_ad_pool:max_pools", 3);
    private static final amd<Integer> dW = amd.a(1, "gads:heap_wastage:bytes", 0);
    private static final amd<Boolean> dX = amd.a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> dY = amd.a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> dZ = amd.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    public static final amd<Integer> da = amd.a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final amd<Boolean> db = amd.a(1, "gads:clearcut_logging:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> dc = amd.a(1, "gads:clearcut_logging:write_to_file", Boolean.valueOf(false));
    public static final amd<Boolean> dd = amd.a(0, "gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> de = amd.a(0, "gad:force_dynamite_loading_enabled", Boolean.valueOf(false));
    public static final amd<Integer> df = amd.a(1, "gad:http_redirect_max_count:times", 8);
    public static final amd<Boolean> dg = amd.a(1, "gads:omid:enabled", Boolean.valueOf(false));
    public static final amd<Boolean> dh = amd.a(1, "gads:nonagon:banner:check_dp_size", Boolean.valueOf(false));
    public static final amd<Long> di = amd.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final amd<String> dj = amd.a(0, "gads:public_beta:traffic_multiplier", BuildConfig.VERSION_NAME);
    public static final amd<Boolean> dk = amd.a(1, "gads:real_test_request:enabled", Boolean.valueOf(true));
    public static final amd<Boolean> dl = amd.a(1, "gads:real_test_request:render_webview_label", Boolean.valueOf(true));
    public static final amd<Boolean> dm = amd.a(1, "gads:real_test_request:render_native_label", Boolean.valueOf(true));
    public static final amd<Integer> dn = amd.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final amd<Integer> do = amd.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    public static final amd<Integer> dp = amd.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    public static final amd<Integer> dq = amd.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    private static final amd<String> dr = amd.a(0, "gads:sdk_core_experiment_id");
    private static final amd<String> ds = amd.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static final amd<Boolean> dt = amd.a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    private static final amd<String> du = amd.a(0, "gads:request_builder:singleton_webview_experiment_id");
    private static final amd<Boolean> dv = amd.a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    private static final amd<String> dw = amd.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    private static final amd<String> dx = amd.a(0, "gads:block_autoclicks_experiment_id");
    private static final amd<String> dy = amd.a(0, "gads:spam_app_context:experiment_id");
    private static final amd<Integer> dz = amd.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final amd<String> e = amd.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    private static final amd<Long> eA = amd.a(1, "gads:cache:javascript_timeout_millis", 5000);
    private static final amd<Boolean> eB = amd.a(1, "gads:cache:connection_per_read", Boolean.valueOf(false));
    private static final amd<Long> eC = amd.a(1, "gads:cache:connection_timeout", 5000);
    private static final amd<Long> eD = amd.a(1, "gads:cache:read_only_connection_timeout", 5000);
    private static final amd<Boolean> eE = amd.a(0, "gads:nonagon:red_button", Boolean.valueOf(false));
    private static final amd<Boolean> eF = amd.a(1, "gads:nonagon:banner:enabled", Boolean.valueOf(false));
    private static final amd<String> eG = amd.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final amd<Boolean> eH = amd.a(1, "gads:nonagon:interstitial:enabled", Boolean.valueOf(false));
    private static final amd<String> eI = amd.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final amd<Boolean> eJ = amd.a(1, "gads:nonagon:rewardedvideo:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> eK = amd.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.valueOf(false));
    private static final amd<String> eL = amd.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final amd<Boolean> eM = amd.a(1, "gads:nonagon:nativead:enabled", Boolean.valueOf(false));
    private static final amd<String> eN = amd.a(1, "gads:nonagon:nativead:app_name", "(?!)");
    private static final amd<Boolean> eO = amd.a(1, "gads:nonagon:service:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> eP = amd.a(1, "gads:signals:ad_id_info:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> eQ = amd.a(1, "gads:signals:app_index:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> eR = amd.a(1, "gads:signals:cache:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> eS = amd.a(1, "gads:signals:doritos:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> eT = amd.a(1, "gads:signals:location:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> eU = amd.a(1, "gads:signals:network_prediction:enabled", Boolean.valueOf(false));
    private static final amd<Boolean> eV = amd.a(1, "gads:signals:parental_control:enabled", Boolean.valueOf(false));
    private static byte[] eW;
    private static final amd<Boolean> ea = amd.a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    private static final amd<String> eb = amd.a(0, "gads:gmsg:video_meta:experiment_id");
    private static final amd<Long> ec = amd.a(1, "gads:network:cache_prediction_duration_s", 300);
    private static final amd<Long> ed = amd.a(1, "gads:rtb_signal_timeout_ms", 1000);
    private static final amd<Boolean> ee = amd.a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    private static final amd<Boolean> ef = amd.a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    private static final amd<String> eg = amd.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static final amd<String> eh = amd.a(1, "gads:sdk_core_constants:experiment_id");
    private static final amd<Boolean> ei = amd.a(1, "gads:js_flags:disable_phenotype", Boolean.valueOf(false));
    private static final amd<String> ej = amd.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static final amd<String> ek = amd.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static final amd<String> el = amd.a(1, "gads:singleton_webview_native:experiment_id");
    private static final amd<Boolean> em = amd.a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    private static final amd<String> en = amd.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    private static final amd<String> eo = amd.b(1, "gads:auto_location_timeout:experiment_id");
    private static final amd<Long> ep = amd.a(1, "gads:auto_location_interval", -1);
    private static final amd<String> eq = amd.b(1, "gads:auto_location_interval:experiment_id");
    private static final amd<String> er = amd.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    private static final amd<String> es = amd.a(0, "gads:afs:csa:experiment_id");
    private static final amd<Boolean> et = amd.a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    private static final amd<Boolean> eu = amd.a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    private static final amd<Boolean> ev = amd.a(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
    private static final amd<String> ew = amd.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static final amd<Long> ex = amd.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    private static final amd<Integer> ey = amd.a(1, "gads:cache:ad_request_timeout_millis", 250);
    private static final amd<Integer> ez = amd.a(1, "gads:cache:max_concurrent_downloads", 10);
    public static final amd<Float> f = amd.a(1, "gads:trapped_exception_sample_rate", 0.01f);
    public static final amd<Boolean> g = amd.a(0, "gads:block_autoclicks", Boolean.valueOf(false));
    public static final amd<String> h = amd.a(1, "gads:video_exo_player:version", "1");
    public static final amd<Integer> i = amd.a(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final amd<Integer> j = amd.a(1, "gads:video_exo_player:read_timeout", 8000);
    public static final amd<Integer> k = amd.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final amd<Integer> l = amd.a(1, "gads:video_exo_player:exo_player_precache_limit", (int) MoPubClientPositioning.NO_REPEAT);
    public static final amd<Integer> m = amd.a(1, "gads:video_exo_player:byte_buffer_precache_limit", (int) MoPubClientPositioning.NO_REPEAT);
    public static final amd<Integer> n = amd.a(1, "gads:video_stream_cache:limit_count", 5);
    public static final amd<Integer> o = amd.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final amd<Integer> p = amd.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final amd<Long> q = amd.a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final amd<Long> r = amd.a(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final amd<Integer> s = amd.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final amd<Boolean> t = amd.a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    public static final amd<String> u = amd.a(1, "gads:video:metric_frame_hash_times", "");
    public static final amd<Long> v = amd.a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final amd<Boolean> w = amd.a(1, "gads:video:force_watermark", Boolean.valueOf(false));
    public static final amd<Long> x = amd.a(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final amd<Boolean> y = amd.a(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    public static final amd<Integer> z = amd.a(1, "gads:video:spinner:scale", 4);

    public static List<String> a() {
        return akc.e().a();
    }

    public static void a(Context context) {
        js.a(context, new amo(context));
        int intValue = ((Integer) akc.f().a(dW)).intValue();
        if (intValue > 0 && eW == null) {
            eW = new byte[intValue];
        }
    }

    public static void a(Context context, int i, JSONObject jSONObject) {
        akc.d();
        Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        akc.e().a(edit, 1, jSONObject);
        akc.d();
        edit.commit();
    }

    public static List<String> b() {
        return akc.e().b();
    }
}
